### PR TITLE
fix decimals fees on bounties

### LINKED ISSUE #8977: bug: Converting from USD to ETH does not work when creating a new bounty
**Describe the bug**
```
raven.js:58 Error: [ethjs-unit] while converting number 0.0018880000000000001 to wei, too many decimal places
    at Object.toWei (web3.min.fbcef5f40431.js:1)
    at Object.toWei (web3.min.fbcef5f40431.js:1)
    at new_bounty.fcedd9fdd8f5.js:432
    at new Promise (<anonymous>)
    at wn.payFees (new_bounty.fcedd9fdd8f5.js:426)
    at wn.submitForm (new_bounty.fcedd9fdd8f5.js:484)
    at click (eval at Ya (vue.c107ca5cd927.js:1), <anonymous>:3:48871)
    at He (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.n (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.Yr.o._wrapper (vue.c107ca5cd927.js:6)
    at HTMLButtonElement.d (raven.js:445)
```

**To Reproduce**
1. Go to https://gitcoin.co/bounty/new
2. Select ETH as denomination, and type 50 into the USD field.
3. Submit form (nothing happens when pressing the button).
  Screen Shot 2021-06-02 at 12 43 08 PM

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

There some situation when the fees get calculated with more than 18 decimals making the Tx to fail.
 
##### Refers/Fixes

Fix #8977

### CODE REVIEW

File: app/assets/v2/js/pages/new_bounty.js [hunk 1]
```diff
@@ -437,7 +437,7 @@ Vue.mixin({
           web3.eth.sendTransaction({
             to: toAddress,
             from: selectedAccount,
-            value: web3.utils.toWei(String(vm.totalAmount.totalFee), 'ether')
+            value: web3.utils.toWei(new web3.utils.BN(BigInt(vm.totalAmount.totalFee.toFixed(18) * 1.0 * Math.pow(10, 18))).toString(), 'wei')
```
Comment (gdixon) [inline app/assets/v2/js/pages/new_bounty.js:440]: We shouldn't need the `* 1.0` part, and could we get away with not using web3 altogether?

`BigInt(vm.totalAmount.totalFee.toFixed(18) * Math.pow(10, 18)).toString()`

Should give us the same result?

Comment (octavioamu) [reply app/assets/v2/js/pages/new_bounty.js:440]: but with BN I believe is a more secure way about gettting what web3 is waiting for, not 100% sure.

**Review by gdixon — APPROVED** [review]
🚀
