### PR TITLE
 Fix markdown of html tags in issue description

### LINKED ISSUE #1667: Bug: Code not visible on website
When an issue contains code it is not displayed by the website:

selection_085

Here you see that there should be embedded code:

selection_086

see: https://gitcoin.co/issue/livepeer/tv/2/709

### PR DESCRIPTION
**Pull request by pinkiebell**
Fixes #1667

### CODE REVIEW

File: app/assets/v2/js/pages/bounty_details.js [hunk 1]
```diff
@@ -834,11 +834,9 @@ const build_uri_for_pull_bounty_from_api = function() {
 };
 
 var pull_bounty_from_api = function() {
-  let all_results = [];
-
   $.get(build_uri_for_pull_bounty_from_api()).then(results => {
-    all_results = sanitizeAPIResults(results);
-    return all_results;
+    // do not sanitize issue_description. showdown will handle that.
+    return sanitizeAPIResults(results, 'issue_description');
```
Comment (owocki) [inline app/assets/v2/js/pages/bounty_details.js]: have you tested that it is not possible to inject `script`s into the bounty page after doing this?

Comment (pinkiebell) [reply app/assets/v2/js/pages/bounty_details.js]: It did just fine with the data from the API.
However you a are right! I tested several inputs and injection is possible.
I will come up with a solution

File: app/assets/v2/js/pages/bounty_details.js [hunk 2]
```diff
@@ -865,11 +865,10 @@ const build_uri_for_pull_bounty_from_api = function() {
...
 
 var pull_bounty_from_api = function() {
-  let all_results = [];
-
   $.get(build_uri_for_pull_bounty_from_api()).then(results => {
-    all_results = sanitizeAPIResults(results);
-    return all_results;
+    // special case: do not sanitize issue_description
+    // before we pass it to the markdown parser
+    return sanitizeAPIResults(results, 'issue_description');
```
Comment (SaptakS) [inline app/assets/v2/js/pages/bounty_details.js]: @pinkiebell Have you tested that no injections are possible?
