### PR TITLE
wallet improvments

### LINKED ISSUE #6931: MetaMask Authentication
**Describe the bug**

When I go to create a grant, the page loads faster than my MetaMask can sync with the page. Thus, the page ends up saying "you need to sync with MetaMask to continue, please refresh page" shortly before my MetaMask syncs.

I refresh the page and then have the same problem, as the page loads faster than the MetaMask sync.

**To Reproduce**

Turn MetaMask on for site -> create a grant page

**Expected behavior**

The expected behavior for the site page to wait so my MetaMask has time to sync before telling me I need to refresh

**Screenshots**

image

image

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Browser Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

On desktop

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

### PR DESCRIPTION
**Pull request by octavioamu**
##### Description

- Remove web3 declaration to use properly the chosen provider by the user on the modal, that was causing a bug on mobile as the web3modal detect web3 is injected and then believes is a web3 browser when actually is not wallet present.
- Fix modal "thanks grant contribution" to use bootstrap modal, with that , scroll, position, background, scrolling and close with ESC get added out of the box.
- Fix js files duplication on some pages with townsquare activity that use tip_dependencies. 
- Fix eslint errors 
- fix grants submitting without wallet. 
- Add wallet listener to avoid bad hoisting and wallet errors enabling the wallet onload.
- fix problem when page init runs before the wallet is ready #6931 (with new wallet listeners and helper functions) 
- fixed forms submitting without connecting first to the wallet 

##### Refers/Fixes
- Fix #6931
- Fix mobile wasn't working in some situations. https://gitcoincore.slack.com/archives/CAXQ7PT60/p1592664171101400
- Probably fix also https://gitcoincore.slack.com/archives/CAXQ7PT60/p1592645887101200
- Stopper for 'decimals' of undefined since now will ask to connect onload and also if you ignore and try to submit will prompt you again without trying to submit the form https://gitcoincore.slack.com/archives/CAXQ7PT60/p1592318730054600

##### Testing

Tested the site where web3 is needed for an action and changed the code to request connect on demand or onload depending the needs of the product: 
Grant flow 
Bounty flow
Tip flow
Kudos Flow
Pages over the site

### CODE REVIEW

File: app/assets/v2/js/grants/funding.js [hunk 1]
```diff
@@ -31,13 +31,6 @@ $(document).ready(function() {
       $('#tweetModal a.button').attr('href', 'https://twitter.com/intent/tweet?text=I%20just%20funded%20these%20' + donations.length + '%20grants%20on%20@gitcoin%20=%3E%20' + bulk_add_cart);
     }
     CartData.setCart([]);
-
-    $(document).keydown(function(e) {
```
Comment (owocki) [inline app/assets/v2/js/grants/funding.js:35]: why remove this?  seems unrelated to wallet stuff

Comment (octavioamu) [reply app/assets/v2/js/grants/funding.js:35]: because I fixed the modal to use properly with bootstrap modal, in that way modal scroll get fixed, pressing ESC close the modal without need to create that functionality also you will find $('#tweetModal').modal('show'); and a new class to make the modal scrollable , that is all from bootstrap modals.

Comment (octavioamu) [reply app/assets/v2/js/grants/funding.js:35]: Im fixing the wallet but with that finding a few things broken, like send.js and tokens.js injected more that 2 times in a few pages like townsquare and grants details.

Comment (octavioamu) [reply app/assets/v2/js/grants/funding.js:35]: updated the description. 
Doing some regression test before I put it ready for review.

File: app/assets/v2/js/pages/fulfill_bounty/index.js [hunk 2]
```diff
@@ -1,4 +1,20 @@
...
+  }
+  $('#payoutAddress').val(selectedAccount);
+  $('#payoutAddress').attr('readonly', true);
+}
+
+window.addEventListener('dataWalletReady', function(e) {
+  if (is_bounties_network) {
+    fetchFromWeb3Wallet();
+  }
+}, false);
```
Comment (thelostone-mc) [inline app/assets/v2/js/pages/fulfill_bounty/index.js:16]: ^ do we wanna just move this into ETH.js + how would this change once we retire std bounties ?
something like 

```
if (is_bounties_network || web3_modal) {
...
}
```

Comment (thelostone-mc) [inline app/assets/v2/js/pages/fulfill_bounty/index.js:16]: ^ do we wanna just move this into ETH.js + how would this change once we retire std bounties ?
something like 

```
if (is_bounties_network || web3_modal) {
...
}
```
